[package]
name = "birthdays"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.9"
chrono = { version = "0.4.38" }
thiserror = "2.0.12"

